
import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { analyzeLabReport } from '../services/geminiService';
import { LabReportAnalysis, LabMetric } from '../types';
import { FileText, Upload, Camera, Loader2, Download, AlertTriangle, CheckCircle, Activity, HeartPulse, ChevronRight, Zap, Sparkles, Save } from 'lucide-react';

export const HealthReports: React.FC = () => {
  const { saveReport, savedReports } = useApp();
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<LabReportAnalysis | null>(null);
  const [error, setError] = useState('');
  const [isSaved, setIsSaved] = useState(false);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = reader.result as string;
        setImage(base64);
        processReport(base64);
      };
      reader.readAsDataURL(file);
    }
  };

  const processReport = async (base64: string) => {
    setLoading(true);
    setError('');
    setAnalysis(null);
    setIsSaved(false);
    try {
      const data = await analyzeLabReport(base64);
      setAnalysis(data);
    } catch (err) {
      setError("Unable to read report. Please ensure text is clear and well-lit.");
    } finally {
      setLoading(false);
    }
  };

  const handleSave = () => {
    if (analysis && !isSaved) {
      saveReport(analysis);
      setIsSaved(true);
    }
  };

  const handleExport = () => {
    if (!analysis) return;
    const text = `
HEALTH REPORT SUMMARY
Date: ${new Date().toLocaleDateString()}
Report Type: ${analysis.title}

SUMMARY:
${analysis.summary}

METRICS:
${analysis.metrics.map(m => `- ${m.name}: ${m.value} ${m.unit} [${m.status}]`).join('\n')}

SUGGESTIONS:
${analysis.insights.map(i => `- ${i.title}: ${i.description}`).join('\n')}

Generated by Med AI
    `;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Health_Report_${Date.now()}.txt`;
    a.click();
  };

  return (
    <div className="space-y-6 pb-24 animate-fade-in">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Health Reports</h1>
        <div className="bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-300 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1 border border-purple-200 dark:border-purple-800">
           <Zap size={12} fill="currentColor" /> Vault Level 3
        </div>
      </div>

      {/* Gamified Header Card */}
      <div className="bg-gradient-to-r from-purple-600 to-indigo-600 rounded-2xl p-6 text-white shadow-lg relative overflow-hidden">
        <div className="absolute right-0 top-0 w-32 h-32 bg-white/10 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2"></div>
        <div className="relative z-10 flex justify-between items-center">
          <div>
            <h2 className="text-lg font-bold mb-1">AI Health Analyzer</h2>
            <p className="text-purple-100 text-xs max-w-[200px]">Upload lab reports to get instant analysis, health insights, and digital storage.</p>
          </div>
          <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm border border-white/20">
             <Activity size={24} />
          </div>
        </div>
      </div>

      {/* Upload Area */}
      {!analysis && !loading && (
        <div className="grid grid-cols-2 gap-4">
          <label className="flex flex-col items-center justify-center p-6 bg-white dark:bg-slate-800 rounded-2xl shadow-sm border-2 border-dashed border-slate-300 dark:border-slate-700 cursor-pointer hover:border-purple-500 dark:hover:border-purple-400 transition-colors group">
            <div className="w-12 h-12 bg-slate-50 dark:bg-slate-700 rounded-full flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
               <Camera className="text-slate-400 dark:text-slate-300" size={24} />
            </div>
            <span className="text-sm font-bold text-slate-600 dark:text-slate-300">Take Photo</span>
            <input type="file" accept="image/*" capture="environment" className="hidden" onChange={handleFileChange} />
          </label>
          
          <label className="flex flex-col items-center justify-center p-6 bg-white dark:bg-slate-800 rounded-2xl shadow-sm border-2 border-dashed border-slate-300 dark:border-slate-700 cursor-pointer hover:border-purple-500 dark:hover:border-purple-400 transition-colors group">
            <div className="w-12 h-12 bg-slate-50 dark:bg-slate-700 rounded-full flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
               <Upload className="text-slate-400 dark:text-slate-300" size={24} />
            </div>
            <span className="text-sm font-bold text-slate-600 dark:text-slate-300">Upload File</span>
            <input type="file" accept="image/*" className="hidden" onChange={handleFileChange} />
          </label>
        </div>
      )}

      {/* Loading State with Scanning Animation */}
      {loading && (
        <div className="flex flex-col items-center justify-center py-12 text-center">
           <div className="relative w-64 h-48 bg-slate-900 rounded-xl overflow-hidden shadow-2xl mb-6">
              {image && <img src={image} className="w-full h-full object-cover opacity-50" alt="Scanning" />}
              <div className="absolute inset-0 bg-gradient-to-b from-transparent via-purple-500/20 to-transparent w-full h-2 animate-[scan_2s_linear_infinite]"></div>
              <div className="absolute inset-0 border-2 border-purple-500/30 rounded-xl"></div>
           </div>
           <h3 className="text-lg font-bold text-slate-800 dark:text-white animate-pulse">Analyzing Report...</h3>
           <p className="text-slate-500 text-sm mt-1">Extracting vital metrics and health data</p>
        </div>
      )}

      {/* Error State */}
      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 p-4 rounded-xl flex items-center gap-3">
          <AlertTriangle size={24} />
          <p className="text-sm font-medium">{error}</p>
          <button onClick={() => setImage(null)} className="ml-auto text-xs font-bold underline">Try Again</button>
        </div>
      )}

      {/* Analysis Results */}
      {analysis && (
        <div className="space-y-6 animate-slide-up">
          
          {/* Header Info */}
          <div className="flex justify-between items-center">
             <div>
               <h2 className="text-xl font-bold text-slate-900 dark:text-white">{analysis.title}</h2>
               <p className="text-xs text-slate-500 dark:text-slate-400">Processed {new Date().toLocaleTimeString()}</p>
             </div>
             <div className="bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1">
                 <CheckCircle size={12} /> Complete
             </div>
          </div>

          {/* Enhanced AI Summary Card */}
          <div className="relative bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-slate-800 dark:to-slate-800 p-6 rounded-2xl border border-indigo-100 dark:border-slate-700 shadow-sm overflow-hidden group">
             {/* Decorative Background Icon */}
             <div className="absolute -top-6 -right-6 opacity-5 dark:opacity-10 group-hover:scale-110 transition-transform duration-500">
                <Sparkles size={120} className="text-indigo-600 dark:text-indigo-400" />
             </div>
             
             <div className="relative z-10">
                <div className="flex items-center gap-2 mb-3">
                   <div className="p-1.5 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-lg shadow-sm">
                      <Sparkles size={16} fill="currentColor" className="opacity-75" />
                   </div>
                   <h3 className="font-bold text-indigo-900 dark:text-indigo-100">AI Summary</h3>
                </div>
                <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-sm font-medium">
                   {analysis.summary}
                </p>
             </div>
          </div>

          {/* Metrics Grid */}
          <div>
            <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-3 px-1">Vital Metrics</h3>
            <div className="grid grid-cols-2 gap-3">
              {analysis.metrics.map((metric, idx) => (
                <div key={idx} className={`p-4 rounded-xl border transition-all ${
                    metric.status === 'High' || metric.status === 'Low' 
                      ? 'bg-red-50 dark:bg-red-900/10 border-red-200 dark:border-red-800 shadow-sm' 
                      : 'bg-white dark:bg-slate-800 border-slate-100 dark:border-slate-700'
                }`}>
                  <div className="flex justify-between items-start mb-2">
                      <span className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase truncate pr-2">{metric.name}</span>
                      {metric.status !== 'Normal' && (
                        <AlertTriangle size={14} className="text-red-500 shrink-0" />
                      )}
                  </div>
                  <div className="flex items-baseline gap-1">
                      <span className={`text-xl font-bold ${
                        metric.status !== 'Normal' ? 'text-red-600 dark:text-red-400' : 'text-slate-900 dark:text-white'
                      }`}>
                        {metric.value}
                      </span>
                      <span className="text-xs text-slate-400">{metric.unit}</span>
                  </div>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full inline-block mt-2 ${
                      metric.status === 'Normal' 
                        ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
                        : 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                  }`}>
                    {metric.status}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* AI Insights */}
          <div>
            <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-3 px-1">Health Suggestions</h3>
            <div className="space-y-3">
              {analysis.insights.map((insight, idx) => (
                <div key={idx} className="bg-white dark:bg-slate-800 p-4 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 flex gap-4 transition-transform hover:scale-[1.01]">
                  <div className="w-10 h-10 bg-purple-50 dark:bg-slate-700 rounded-full flex items-center justify-center text-xl shrink-0">
                    {insight.icon}
                  </div>
                  <div>
                    <h4 className="font-bold text-slate-900 dark:text-white text-sm">{insight.title}</h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed">{insight.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
             <button 
               onClick={() => { setAnalysis(null); setImage(null); setIsSaved(false); }}
               className="flex-1 py-3 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 font-bold rounded-xl hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
             >
               Scan New
             </button>
             <button 
               onClick={handleSave}
               disabled={isSaved}
               className={`flex-1 py-3 rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg transition-all active:scale-95 ${
                 isSaved 
                 ? 'bg-green-600 text-white cursor-default'
                 : 'bg-primary-600 hover:bg-primary-700 text-white'
               }`}
             >
               {isSaved ? <CheckCircle size={18} /> : <Save size={18} />}
               {isSaved ? 'Saved' : 'Save Profile'}
             </button>
             <button 
               onClick={handleExport}
               className="flex-1 py-3 bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-bold rounded-xl flex items-center justify-center gap-2 shadow-lg hover:shadow-xl transition-all active:scale-95"
             >
               <Download size={18} /> Export
             </button>
          </div>

        </div>
      )}
      
      <style>{`
        @keyframes scan {
          0% { top: 0; }
          100% { top: 100%; }
        }
      `}</style>
    </div>
  );
};
